# Generated by Django 3.0.5 on 2020-04-28 01:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_post_users'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='users',
            new_name='like_users',
        ),
    ]
